# Generated by Django 3.2.6 on 2021-08-22 11:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twitter', '0002_tweet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactModel',
        ),
        migrations.RenameModel(
            old_name='Tweet',
            new_name='TweetModel',
        ),
    ]
